# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_auto_20161121_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='picture',
            new_name='image',
        ),
    ]
