# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_auto_20161122_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pending',
        ),
    ]
