# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import shopping.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_auto_20161126_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='zipcode',
            field=models.IntegerField(default=11111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=shopping.models.random_price),
        ),
    ]
