# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0016_auto_20161127_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ref_id',
            field=models.IntegerField(default=400000000),
            preserve_default=False,
        ),
    ]
