# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0017_item_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
