# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0019_auto_20161128_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
