# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0024_auto_20161129_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
